name: Convert Markdown to HTML

on:
  push:
    branches:
    - main

env:
  DDT_PATH: books/ddt/

jobs:
  convert-to-html:
    name: Convert Markdown to HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        run: |
          echo $RUNNER_OS
          echo ${{ env.DDT_PATH }}

#      - run: npm i markdown-to-html-cli -g
#      - run: markdown-to-html --source 0.md --output 0.html
#
#      - name: Convert
#        uses: jaywcjlove/markdown-to-html-cli@main
#        with:
#          source: $DDT_PATH/0.md
#          output: $DDT_PATH/0.html
#
#          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
#          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>

      - name: Manipulate
        run: |
          date > date.txt
#          sed -i -e 's/dark="Dark"/dark="Ніч"/' $DDT_PATH/0.html
#          sed -i -e 's/light="Light"/light="День"/' $DDT_PATH/0.html

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Convert Markdown to HTML' --no-verify
          git push
