name: Convert Markdown to HTML

on:
  push:
    branches:
    - main

jobs:
  convert-to-html:
    name: Convert Markdown to HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git pull --rebase --squash --no-edit
      - run: npm i markdown-to-html-cli -g
      - run: markdown-to-html --source 0.md --output 0.html
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Convert Markdown to HTML' --no-verify
          git push
# or
#- name: Converts Markdown to HTML
#  uses: jaywcjlove/markdown-to-html-cli@main
#  with:
#    source: README-zh.md
#    output: coverage/action.html
#    github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
#    favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg> 
