name: Convert Markdown to HTML

on:
  push:
    branches:
    - main

jobs:
  convert-to-html:
    name: Convert Markdown to HTML
    runs-on: ubuntu-latest
    env:
      working-directory: ./books/ddt/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show
        working-directory: ${{ env.working-directory }}
        run: |
          ls [0-9]*.md | cut -f1 | sort -u | xargs cat > index.md

#      - run: npm i markdown-to-html-cli -g
#      - run: markdown-to-html --source 0.md --output 0.html
#
      - name: Convert
        uses: jaywcjlove/markdown-to-html-cli@main
        working-directory: ${{ env.working-directory }}
        with:
          source: index.md
          output: index.html
#
#          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
#          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>

      - name: Manipulate
        run: |
          date > date.txt
#          sed -i -e 's/dark="Dark"/dark="Ніч"/' index.html
#          sed -i -e 's/light="Light"/light="День"/' index.html

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Convert Markdown to HTML' --no-verify
          git push
