name: Convert Markdown to HTML

on:
  push:
    branches:
    - main

jobs:
  convert-to-html:
    name: Convert Markdown to HTML
    runs-on: ubuntu-latest
    env:
      interim-file: index.md
      target-file: index.html
      css-path: /css/main.css
      font-family: custom
      working-directory: ./books/ddt
      source-directory: source
    steps:
      - name: Record the date
        run: |
          date > date.txt

      - name: Checkout
        uses: actions/checkout@v3

      - name: Concatenate the markdowns
        working-directory: ${{ env.working-directory }}
        run: |
          ls [0-9]*.md | cut -f1 | sort -u | xargs cat > ${{ env.interim-file }}

#      - run: npm i markdown-to-html-cli -g
#      - run: markdown-to-html --source 0.md --output 0.html
      - name: Convert
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.working-directory }}/${{ env.interim-file }}
          output: ${{ env.working-directory }}/${{ env.target-file }}
#          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
#          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>

      - name: Manipulate
        working-directory: ${{ env.working-directory }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's/"\([0-9]\+\).md"/"#\1"/' ${{ env.target-file }}
          sed -i -e 's/<\/head>/yo<\/head>/' ${{ env.target-file }}
#          sed -i -e 's/<\/head>/\n    <link rel="stylesheet" href="${{ env.css-path }}">\n<\/head>/' ${{ env.target-file }}
#          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}

      - name: Convert source
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.working-directory }}/${{ env.source-directory }}/${{ env.interim-file }}
          output: ${{ env.working-directory }}/${{ env.source-directory }}/${{ env.target-file }}

      - name: Manipulate source
        working-directory: ${{ env.working-directory }}/${{ env.source-directory }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Convert Markdown to HTML' --no-verify
          git push
