name: Convert Markdown to HTML

on:
  push:
    branches:
    - main

jobs:
  convert-to-html:
    name: Convert Markdown to HTML
    runs-on: ubuntu-latest
    env:
      source-file: index.md
      interim-file: index.md
      target-file: index.html
      css-path: /css/main.css
      font-family: custom
      dir-main: ./
      dir-books-1: ./books/ddt
      dir-tools-1: ./tools/links
      dir-tools-2: ./tools/wordships
      source-directory: source
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert ${{ env.dir-main }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-main }}/${{ env.source-file }}
          output: ${{ env.dir-main }}/${{ env.target-file }}
          favicon: ./2.svg

      - name: Manipulate ${{ env.dir-main }}
        working-directory: ${{ env.dir-main }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}


      - name: Concatenate the markdowns of ${{ env.dir-books-1 }}
        working-directory: ${{ env.dir-books-1 }}
        run: |
          ls [0-9]*.md | cut -f1 | sort -u | xargs cat > ${{ env.interim-file }}

      - name: Convert ${{ env.dir-books-1 }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-books-1 }}/${{ env.interim-file }}
          output: ${{ env.dir-books-1 }}/${{ env.target-file }}
          favicon: data:image/svg+xml,<svg version=%221.1%22 xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 width=%22100%22 viewBox=%220 0 100 100%22><defs><filter id=%22outline-indigo%22><feMorphology in=%22SourceAlpha%22 result=%22expanded%22 operator=%22dilate%22 radius=%223%22></feMorphology><feFlood flood-color=%22indigo%22 result=%22indi%22></feFlood><feComposite in=%22indi%22 in2=%22expanded%22 operator=%22in%22></feComposite><feComposite in=%22SourceGraphic%22></feComposite></filter><clipPath id=%22emojiClipPath%22><text filter=%22url(#filter)%22 x=%2235%22 y=%2295%22 font-family=%22Georgia%22 font-weight=%22bold%22 font-size=%226em%22 fill=%22#000000%22>Ї</text></clipPath></defs><g filter=%22url(#outline-indigo)%22><rect y=%220%22 width=%22100%22 height=%22100%22 fill=%22yellow%22 clip-path=%22url(#emojiClipPath)%22></rect></g></svg>

      - name: Manipulate ${{ env.dir-books-1 }}
        working-directory: ${{ env.dir-books-1 }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's/"\([0-9]\+\).md"/"#\1"/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}


      - name: Convert ${{ env.dir-tools-1 }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-tools-1 }}/${{ env.source-file }}
          output: ${{ env.dir-tools-1 }}/${{ env.target-file }}
          favicon: data:image/svg+xml,<svg version=%221.1%22 xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 width=%22100%22 viewBox=%220 0 100 100%22><defs><filter id=%22outline-indigo%22><feMorphology in=%22SourceAlpha%22 result=%22expanded%22 operator=%22dilate%22 radius=%223%22></feMorphology><feFlood flood-color=%22indigo%22 result=%22indi%22></feFlood><feComposite in=%22indi%22 in2=%22expanded%22 operator=%22in%22></feComposite><feComposite in=%22SourceGraphic%22></feComposite></filter><clipPath id=%22emojiClipPath%22><text filter=%22url(#filter)%22 x=%2235%22 y=%2295%22 font-family=%22Georgia%22 font-weight=%22bold%22 font-size=%226em%22 fill=%22#000000%22>Ї</text></clipPath></defs><g filter=%22url(#outline-indigo)%22><rect y=%220%22 width=%22100%22 height=%22100%22 fill=%22yellow%22 clip-path=%22url(#emojiClipPath)%22></rect></g></svg>

      - name: Manipulate ${{ env.dir-tools-1 }}
        working-directory: ${{ env.dir-tools-1 }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}


      - name: Convert ${{ env.dir-tools-2 }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-tools-2 }}/${{ env.source-file }}
          output: ${{ env.dir-tools-2 }}/${{ env.target-file }}
          favicon: data:image/svg+xml,<svg version=%221.1%22 xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 width=%22100%22 viewBox=%220 0 100 100%22><defs><filter id=%22outline-indigo%22><feMorphology in=%22SourceAlpha%22 result=%22expanded%22 operator=%22dilate%22 radius=%223%22></feMorphology><feFlood flood-color=%22indigo%22 result=%22indi%22></feFlood><feComposite in=%22indi%22 in2=%22expanded%22 operator=%22in%22></feComposite><feComposite in=%22SourceGraphic%22></feComposite></filter><clipPath id=%22emojiClipPath%22><text filter=%22url(#filter)%22 x=%2235%22 y=%2295%22 font-family=%22Georgia%22 font-weight=%22bold%22 font-size=%226em%22 fill=%22#000000%22>Ї</text></clipPath></defs><g filter=%22url(#outline-indigo)%22><rect y=%220%22 width=%22100%22 height=%22100%22 fill=%22yellow%22 clip-path=%22url(#emojiClipPath)%22></rect></g></svg>

      - name: Manipulate ${{ env.dir-tools-2 }}
        working-directory: ${{ env.dir-tools-2 }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}


      - name: Commit
        run: |
          date > date.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Convert Markdown to HTML' --no-verify
          git pull --rebase
          git push
