name: Convert Markdown to HTML

on:
  push:
    branches:
    - main

jobs:
  convert-to-html:
    name: Convert Markdown to HTML
    runs-on: ubuntu-latest
    env:
      source-file: index.md
      interim-file: index.md
      target-file: index.html
      css-path: /css/main.css
      font-family: custom
      dir-main: ./
      dir-books-1: ./books/ddt
      dir-tools-1: ./tools/links
      dir-tools-2: ./tools/wordships
      source-directory: source
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert ${{ env.dir-main }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-main }}/${{ env.source-file }}
          output: ${{ env.dir-main }}/${{ env.target-file }}
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>[Ð‡]</text></svg>

      - name: Manipulate ${{ env.dir-main }}
        working-directory: ${{ env.dir-main }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}


      - name: Concatenate the markdowns of ${{ env.dir-books-1 }}
        working-directory: ${{ env.dir-books-1 }}
        run: |
          ls [0-9]*.md | cut -f1 | sort -u | xargs cat > ${{ env.interim-file }}

      - name: Convert ${{ env.dir-books-1 }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-books-1 }}/${{ env.interim-file }}
          output: ${{ env.dir-books-1 }}/${{ env.target-file }}
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>ðŸ‡ºðŸ‡¦</text></svg>

      - name: Manipulate ${{ env.dir-books-1 }}
        working-directory: ${{ env.dir-books-1 }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's/"\([0-9]\+\).md"/"#\1"/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}

      - name: Convert source of ${{ env.dir-books-1 }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-books-1 }}/${{ env.source-directory }}/${{ env.interim-file }}
          output: ${{ env.dir-books-1 }}/${{ env.source-directory }}/${{ env.target-file }}

      - name: Manipulate source of ${{ env.dir-books-1 }}
        working-directory: ${{ env.dir-books-1 }}/${{ env.source-directory }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}


      - name: Convert ${{ env.dir-tools-1 }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-tools-1 }}/${{ env.source-file }}
          output: ${{ env.dir-tools-1 }}/${{ env.target-file }}
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>Ð‡</text></svg>

      - name: Manipulate ${{ env.dir-tools-1 }}
        working-directory: ${{ env.dir-tools-1 }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}


      - name: Convert ${{ env.dir-tools-2 }}
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ${{ env.dir-tools-2 }}/${{ env.source-file }}
          output: ${{ env.dir-tools-2 }}/${{ env.target-file }}
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>Ð‡</text></svg>

      - name: Manipulate ${{ env.dir-tools-2 }}
        working-directory: ${{ env.dir-tools-2 }}
        run: |
          sed -i -e 's/dark="Dark"/dark=""/' ${{ env.target-file }}
          sed -i -e 's/light="Light"/light=""/' ${{ env.target-file }}
          sed -i -e 's|</head>|\n    <link rel="stylesheet" href="${{ env.css-path }}">\n</head>|' ${{ env.target-file }}
          sed -i -e 's/font-family: /font-family: ${{ env.font-family }}\,/' ${{ env.target-file }}
          sed -i -e 's/position: fixed/position: relative/' ${{ env.target-file }}


      - name: Commit
        run: |
          date > date.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Convert Markdown to HTML' --no-verify
          git pull --rebase
          git push
